using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace datalink_msgs
    {
        public class CompressedPointCloud2 : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "CompressedPointCloud2";
            public readonly string md5sum = "ca4ef319b3972275bb667263a2e57c9f";
            public std_msgs.Header header;
            public System.UInt32 height;
            public System.UInt32 width;
            public List<sensor_msgs.PointField> fields;
            public bool is_bigendian;
            public System.UInt32 point_step;
            public System.UInt32 row_step;
            public readonly System.Byte PC60 = 17;
            public readonly System.Byte PC30 = 16;
            public readonly System.Byte PCL = 2;
            public readonly System.Byte ZLIB = 1;
            public readonly System.Byte NONE = 0;
            public System.Byte compression_type;
            public List<System.Byte> compressed_data;
            public bool is_dense;

            public CompressedPointCloud2 ()
            {
                header = new std_msgs.Header();
                height = 0;
                width = 0;
                fields = new List<sensor_msgs.PointField>();
                is_bigendian = false;
                point_step = 0;
                row_step = 0;
                compression_type = 0;
                compressed_data = new List<System.Byte>();
                is_dense = false;
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += "height: " + Convert.ToString(height) + "\n";
                string_rep += "width: " + Convert.ToString(width) + "\n";
                string_rep += "fields:\n[";
                foreach (sensor_msgs.PointField element in fields)
                {
                    string_rep += " " + element.ToStringRaw();
                }
                string_rep += "]\n\n";
                string_rep += "is_bigendian: " + Convert.ToString(is_bigendian) + "\n";
                string_rep += "point_step: " + Convert.ToString(point_step) + "\n";
                string_rep += "row_step: " + Convert.ToString(row_step) + "\n";
                string_rep += "compression_type: " + Convert.ToString(compression_type) + "\n";
                string_rep += "compressed_data:\n[";
                foreach (System.Byte element in compressed_data)
                {
                    string_rep += " " + Convert.ToString(element);
                }
                string_rep += "]\n\n";
                string_rep += "is_dense: " + Convert.ToString(is_dense) + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                System.Byte[] height_bytes = BitConverter.GetBytes(height);
                stream.Write(height_bytes, 0, height_bytes.Length);
                System.Byte[] width_bytes = BitConverter.GetBytes(width);
                stream.Write(width_bytes, 0, width_bytes.Length);
                System.Byte[] fields_len_bytes = BitConverter.GetBytes((System.UInt32)fields.Count);
                stream.Write(fields_len_bytes, 0, fields_len_bytes.Length);
                foreach(sensor_msgs.PointField element in fields)
                {
                    element.Serialize(stream);
                }
                System.Byte[] is_bigendian_bytes = BitConverter.GetBytes(is_bigendian);
                stream.Write(is_bigendian_bytes, 0, is_bigendian_bytes.Length);
                System.Byte[] point_step_bytes = BitConverter.GetBytes(point_step);
                stream.Write(point_step_bytes, 0, point_step_bytes.Length);
                System.Byte[] row_step_bytes = BitConverter.GetBytes(row_step);
                stream.Write(row_step_bytes, 0, row_step_bytes.Length);
                System.Byte[] compression_type_bytes = new System.Byte[] {compression_type};
                stream.Write(compression_type_bytes, 0, compression_type_bytes.Length);
                System.Byte[] compressed_data_bytes = compressed_data.ToArray();
                System.Byte[] compressed_data_len_bytes = BitConverter.GetBytes((System.UInt32)compressed_data_bytes.Length);
                stream.Write(compressed_data_len_bytes, 0, compressed_data_len_bytes.Length);
                stream.Write(compressed_data_bytes, 0, compressed_data_bytes.Length);
                System.Byte[] is_dense_bytes = BitConverter.GetBytes(is_dense);
                stream.Write(is_dense_bytes, 0, is_dense_bytes.Length);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                height = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(height).Length;
                width = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(width).Length;
                System.UInt32 fields_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(fields_len).Length;
                for (int i = 0; i < (int)fields_len; i++)
                {
                    sensor_msgs.PointField element = new sensor_msgs.PointField();
                    curIndex += element.Deserialize(serialized, curIndex);
                    fields.Add(element);
                }
                is_bigendian = Convert.ToBoolean(serialized[curIndex]);
                curIndex++;
                point_step = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(point_step).Length;
                row_step = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(row_step).Length;
                compression_type = serialized[curIndex];
                curIndex++;
                System.UInt32 compressed_data_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(compressed_data_len).Length;
                System.Byte[] temp = new System.Byte[compressed_data_len];
                Array.Copy(serialized, curIndex, temp, 0, compressed_data_len);
                compressed_data = temp.ToList();
                curIndex += (int)compressed_data_len;
                is_dense = Convert.ToBoolean(serialized[curIndex]);
                curIndex++;
                return (curIndex - startIndex);
            }

        }
    }
}
