using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace sensor_msgs
    {
        public class CompressedImage : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "CompressedImage";
            public readonly string md5sum = "8f7a12909da2c9d3332d540a0977563f";
            public std_msgs.Header header;
            public string format;
            public List<System.Byte> data;

            public CompressedImage ()
            {
                header = new std_msgs.Header();
                format = "";
                data = new List<System.Byte>();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += "format: " + format + "\n";
                string_rep += "data:\n[";
                foreach (System.Byte element in data)
                {
                    string_rep += " " + Convert.ToString(element);
                }
                string_rep += "]\n\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                System.Byte[] format_bytes = System.Text.Encoding.UTF8.GetBytes(format);
                System.Byte[] format_len_bytes = BitConverter.GetBytes((System.UInt32)format_bytes.Length);
                stream.Write(format_len_bytes, 0, format_len_bytes.Length);
                stream.Write(format_bytes, 0, format_bytes.Length);
                System.Byte[] data_bytes = data.ToArray();
                System.Byte[] data_len_bytes = BitConverter.GetBytes((System.UInt32)data_bytes.Length);
                stream.Write(data_len_bytes, 0, data_len_bytes.Length);
                stream.Write(data_bytes, 0, data_bytes.Length);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                System.UInt32 format_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(format_len).Length;
                format = System.Text.Encoding.UTF8.GetString(serialized, curIndex, (int)format_len);
                curIndex += (int)format_len;
                System.UInt32 data_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(data_len).Length;
                System.Byte[] temp = new System.Byte[data_len];
                Array.Copy(serialized, curIndex, temp, 0, data_len);
                data = temp.ToList();
                curIndex += (int)data_len;
                return (curIndex - startIndex);
            }

        }
    }
}
