using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace sensor_msgs
    {
        public class Illuminance : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "Illuminance";
            public readonly string md5sum = "8cf5febb0952fca9d650c3d11a81a188";
            public std_msgs.Header header;
            public double illuminance;
            public double variance;

            public Illuminance ()
            {
                header = new std_msgs.Header();
                illuminance = 0.0;
                variance = 0.0;
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += "illuminance: " + Convert.ToString(illuminance) + "\n";
                string_rep += "variance: " + Convert.ToString(variance) + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                System.Byte[] illuminance_bytes = BitConverter.GetBytes(illuminance);
                stream.Write(illuminance_bytes, 0, illuminance_bytes.Length);
                System.Byte[] variance_bytes = BitConverter.GetBytes(variance);
                stream.Write(variance_bytes, 0, variance_bytes.Length);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                illuminance = BitConverter.ToDouble(serialized, curIndex);
                curIndex += BitConverter.GetBytes(illuminance).Length;
                variance = BitConverter.ToDouble(serialized, curIndex);
                curIndex += BitConverter.GetBytes(variance).Length;
                return (curIndex - startIndex);
            }

        }
    }
}
