using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace std_msgs
    {
        public class Int8MultiArray : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "Int8MultiArray";
            public readonly string md5sum = "d7c1af35a1b4781bbe79e03dd94b7c13";
            public std_msgs.MultiArrayLayout layout;
            public List<System.SByte> data;

            public Int8MultiArray ()
            {
                layout = new std_msgs.MultiArrayLayout();
                data = new List<System.SByte>();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += layout.ToStringRaw() + "\n";
                string_rep += "data:\n[";
                foreach (System.SByte element in data)
                {
                    string_rep += " " + Convert.ToString(element);
                }
                string_rep += "]\n\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                layout.Serialize(stream);
                System.SByte[] signed_temp_data = data.ToArray();
                System.Byte[] unsigned_temp_data = new System.Byte[signed_temp_data.Length];
                Buffer.BlockCopy(signed_temp_data, 0, unsigned_temp_data, 0, signed_temp_data.Length);
                System.Byte[] data_bytes = unsigned_temp_data;
                System.Byte[] data_len_bytes = BitConverter.GetBytes((System.UInt32)data_bytes.Length);
                stream.Write(data_len_bytes, 0, data_len_bytes.Length);
                stream.Write(data_bytes, 0, data_bytes.Length);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += layout.Deserialize(serialized, curIndex);
                System.UInt32 data_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(data_len).Length;
                System.SByte[] temp = new System.SByte[data_len];
                Buffer.BlockCopy(serialized, curIndex, temp, 0, (System.Int32)data_len);
                data = temp.ToList();
                curIndex += (int)data_len;
                return (curIndex - startIndex);
            }

        }
    }
}
