using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace sensor_msgs
    {
        public class Joy : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "Joy";
            public readonly string md5sum = "5a9ea5f83505693b71e785041e67a8bb";
            public std_msgs.Header header;
            public List<float> axes;
            public List<System.Int32> buttons;

            public Joy ()
            {
                header = new std_msgs.Header();
                axes = new List<float>();
                buttons = new List<System.Int32>();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += "axes:\n[";
                foreach (float element in axes)
                {
                    string_rep += " " + Convert.ToString(element);
                }
                string_rep += "]\n\n";
                string_rep += "buttons:\n[";
                foreach (System.Int32 element in buttons)
                {
                    string_rep += " " + Convert.ToString(element);
                }
                string_rep += "]\n\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                System.Byte[] axes_len_bytes = BitConverter.GetBytes((System.UInt32)axes.Count);
                stream.Write(axes_len_bytes, 0, axes_len_bytes.Length);
                foreach(float element in axes)
                {
                    System.Byte[] element_bytes = BitConverter.GetBytes(element);
                    stream.Write(element_bytes, 0, element_bytes.Length);
                }
                System.Byte[] buttons_len_bytes = BitConverter.GetBytes((System.UInt32)buttons.Count);
                stream.Write(buttons_len_bytes, 0, buttons_len_bytes.Length);
                foreach(System.Int32 element in buttons)
                {
                    System.Byte[] element_bytes = BitConverter.GetBytes(element);
                    stream.Write(element_bytes, 0, element_bytes.Length);
                }
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                System.UInt32 axes_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(axes_len).Length;
                for (int i = 0; i < (int)axes_len; i++)
                {
                    float element = BitConverter.ToSingle(serialized, curIndex);
                    curIndex += BitConverter.GetBytes(element).Length;
                    axes.Add(element);
                }
                System.UInt32 buttons_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(buttons_len).Length;
                for (int i = 0; i < (int)buttons_len; i++)
                {
                    System.Int32 element = BitConverter.ToInt32(serialized, curIndex);
                    curIndex += BitConverter.GetBytes(element).Length;
                    buttons.Add(element);
                }
                return (curIndex - startIndex);
            }

        }
    }
}
