using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace sensor_msgs
    {
        public class LaserEcho : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "LaserEcho";
            public readonly string md5sum = "8bc5ae449b200fba4d552b4225586696";
            public List<float> echoes;

            public LaserEcho ()
            {
                echoes = new List<float>();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += "echoes:\n[";
                foreach (float element in echoes)
                {
                    string_rep += " " + Convert.ToString(element);
                }
                string_rep += "]\n\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                System.Byte[] echoes_len_bytes = BitConverter.GetBytes((System.UInt32)echoes.Count);
                stream.Write(echoes_len_bytes, 0, echoes_len_bytes.Length);
                foreach(float element in echoes)
                {
                    System.Byte[] element_bytes = BitConverter.GetBytes(element);
                    stream.Write(element_bytes, 0, element_bytes.Length);
                }
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                System.UInt32 echoes_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(echoes_len).Length;
                for (int i = 0; i < (int)echoes_len; i++)
                {
                    float element = BitConverter.ToSingle(serialized, curIndex);
                    curIndex += BitConverter.GetBytes(element).Length;
                    echoes.Add(element);
                }
                return (curIndex - startIndex);
            }

        }
    }
}
