using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace sensor_msgs
    {
        public class MagneticField : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "MagneticField";
            public readonly string md5sum = "2f3b0b43eed0c9501de0fa3ff89a45aa";
            public std_msgs.Header header;
            public geometry_msgs.Vector3 magnetic_field;
            public double[] magnetic_field_covariance;

            public MagneticField ()
            {
                header = new std_msgs.Header();
                magnetic_field = new geometry_msgs.Vector3();
                magnetic_field_covariance = new double[9];
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += magnetic_field.ToStringRaw() + "\n";
                string_rep += "magnetic_field_covariance: " + magnetic_field_covariance + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                magnetic_field.Serialize(stream);
                foreach(double element in magnetic_field_covariance)
                {
                    System.Byte[] element_bytes = BitConverter.GetBytes(element);
                    stream.Write(element_bytes, 0, element_bytes.Length);
                }
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                curIndex += magnetic_field.Deserialize(serialized, curIndex);
                for (int i = 0; i < (int)magnetic_field_covariance.Length; i++)
                {
                    magnetic_field_covariance[i] = BitConverter.ToDouble(serialized, curIndex);
                    curIndex += BitConverter.GetBytes(magnetic_field_covariance[i]).Length;
                }
                return (curIndex - startIndex);
            }

        }
    }
}
