using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace trajectory_msgs
    {
        public class MultiDOFJointTrajectory : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "MultiDOFJointTrajectory";
            public readonly string md5sum = "ef145a45a5f47b77b7f5cdde4b16c942";
            public std_msgs.Header header;
            public List<string> joint_names;
            public List<trajectory_msgs.MultiDOFJointTrajectoryPoint> points;

            public MultiDOFJointTrajectory ()
            {
                header = new std_msgs.Header();
                joint_names = new List<string>();
                points = new List<trajectory_msgs.MultiDOFJointTrajectoryPoint>();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += "joint_names:\n[";
                foreach (string element in joint_names)
                {
                    string_rep += " " + element;
                }
                string_rep += "]\n\n";
                string_rep += "points:\n[";
                foreach (trajectory_msgs.MultiDOFJointTrajectoryPoint element in points)
                {
                    string_rep += " " + element.ToStringRaw();
                }
                string_rep += "]\n\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                System.Byte[] joint_names_len_bytes = BitConverter.GetBytes((System.UInt32)joint_names.Count);
                stream.Write(joint_names_len_bytes, 0, joint_names_len_bytes.Length);
                foreach(string element in joint_names)
                {
                    System.Byte[] element_bytes = System.Text.Encoding.UTF8.GetBytes(element);
                    System.Byte[] element_len_bytes = BitConverter.GetBytes((System.UInt32)element_bytes.Length);
                    stream.Write(element_len_bytes, 0, element_len_bytes.Length);
                    stream.Write(element_bytes, 0, element_bytes.Length);
                }
                System.Byte[] points_len_bytes = BitConverter.GetBytes((System.UInt32)points.Count);
                stream.Write(points_len_bytes, 0, points_len_bytes.Length);
                foreach(trajectory_msgs.MultiDOFJointTrajectoryPoint element in points)
                {
                    element.Serialize(stream);
                }
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                System.UInt32 joint_names_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(joint_names_len).Length;
                for (int i = 0; i < (int)joint_names_len; i++)
                {
                    System.UInt32 element_len = BitConverter.ToUInt32(serialized, curIndex);
                    curIndex += BitConverter.GetBytes(element_len).Length;
                    string element = System.Text.Encoding.UTF8.GetString(serialized, curIndex, (int)element_len);
                    curIndex += (int)element_len;
                    joint_names.Add(element);
                }
                System.UInt32 points_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(points_len).Length;
                for (int i = 0; i < (int)points_len; i++)
                {
                    trajectory_msgs.MultiDOFJointTrajectoryPoint element = new trajectory_msgs.MultiDOFJointTrajectoryPoint();
                    curIndex += element.Deserialize(serialized, curIndex);
                    points.Add(element);
                }
                return (curIndex - startIndex);
            }

        }
    }
}
