using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace sensor_msgs
    {
        public class PointCloud2 : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "PointCloud2";
            public readonly string md5sum = "1158d486dd51d683ce2f1be655c3c181";
            public std_msgs.Header header;
            public System.UInt32 height;
            public System.UInt32 width;
            public List<sensor_msgs.PointField> fields;
            public bool is_bigendian;
            public System.UInt32 point_step;
            public System.UInt32 row_step;
            public List<System.Byte> data;
            public bool is_dense;

            public PointCloud2 ()
            {
                header = new std_msgs.Header();
                height = 0;
                width = 0;
                fields = new List<sensor_msgs.PointField>();
                is_bigendian = false;
                point_step = 0;
                row_step = 0;
                data = new List<System.Byte>();
                is_dense = false;
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += "height: " + Convert.ToString(height) + "\n";
                string_rep += "width: " + Convert.ToString(width) + "\n";
                string_rep += "fields:\n[";
                foreach (sensor_msgs.PointField element in fields)
                {
                    string_rep += " " + element.ToStringRaw();
                }
                string_rep += "]\n\n";
                string_rep += "is_bigendian: " + Convert.ToString(is_bigendian) + "\n";
                string_rep += "point_step: " + Convert.ToString(point_step) + "\n";
                string_rep += "row_step: " + Convert.ToString(row_step) + "\n";
                string_rep += "data:\n[";
                foreach (System.Byte element in data)
                {
                    string_rep += " " + Convert.ToString(element);
                }
                string_rep += "]\n\n";
                string_rep += "is_dense: " + Convert.ToString(is_dense) + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                System.Byte[] height_bytes = BitConverter.GetBytes(height);
                stream.Write(height_bytes, 0, height_bytes.Length);
                System.Byte[] width_bytes = BitConverter.GetBytes(width);
                stream.Write(width_bytes, 0, width_bytes.Length);
                System.Byte[] fields_len_bytes = BitConverter.GetBytes((System.UInt32)fields.Count);
                stream.Write(fields_len_bytes, 0, fields_len_bytes.Length);
                foreach(sensor_msgs.PointField element in fields)
                {
                    element.Serialize(stream);
                }
                System.Byte[] is_bigendian_bytes = BitConverter.GetBytes(is_bigendian);
                stream.Write(is_bigendian_bytes, 0, is_bigendian_bytes.Length);
                System.Byte[] point_step_bytes = BitConverter.GetBytes(point_step);
                stream.Write(point_step_bytes, 0, point_step_bytes.Length);
                System.Byte[] row_step_bytes = BitConverter.GetBytes(row_step);
                stream.Write(row_step_bytes, 0, row_step_bytes.Length);
                System.Byte[] data_bytes = data.ToArray();
                System.Byte[] data_len_bytes = BitConverter.GetBytes((System.UInt32)data_bytes.Length);
                stream.Write(data_len_bytes, 0, data_len_bytes.Length);
                stream.Write(data_bytes, 0, data_bytes.Length);
                System.Byte[] is_dense_bytes = BitConverter.GetBytes(is_dense);
                stream.Write(is_dense_bytes, 0, is_dense_bytes.Length);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                height = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(height).Length;
                width = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(width).Length;
                System.UInt32 fields_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(fields_len).Length;
                for (int i = 0; i < (int)fields_len; i++)
                {
                    sensor_msgs.PointField element = new sensor_msgs.PointField();
                    curIndex += element.Deserialize(serialized, curIndex);
                    fields.Add(element);
                }
                is_bigendian = Convert.ToBoolean(serialized[curIndex]);
                curIndex++;
                point_step = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(point_step).Length;
                row_step = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(row_step).Length;
                System.UInt32 data_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(data_len).Length;
                System.Byte[] temp = new System.Byte[data_len];
                Array.Copy(serialized, curIndex, temp, 0, data_len);
                data = temp.ToList();
                curIndex += (int)data_len;
                is_dense = Convert.ToBoolean(serialized[curIndex]);
                curIndex++;
                return (curIndex - startIndex);
            }

        }
    }
}
