using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace geometry_msgs
    {
        public class Polygon : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "Polygon";
            public readonly string md5sum = "cd60a26494a087f577976f0329fa120e";
            public List<geometry_msgs.Point32> points;

            public Polygon ()
            {
                points = new List<geometry_msgs.Point32>();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += "points:\n[";
                foreach (geometry_msgs.Point32 element in points)
                {
                    string_rep += " " + element.ToStringRaw();
                }
                string_rep += "]\n\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                System.Byte[] points_len_bytes = BitConverter.GetBytes((System.UInt32)points.Count);
                stream.Write(points_len_bytes, 0, points_len_bytes.Length);
                foreach(geometry_msgs.Point32 element in points)
                {
                    element.Serialize(stream);
                }
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                System.UInt32 points_len = BitConverter.ToUInt32(serialized, curIndex);
                curIndex += BitConverter.GetBytes(points_len).Length;
                for (int i = 0; i < (int)points_len; i++)
                {
                    geometry_msgs.Point32 element = new geometry_msgs.Point32();
                    curIndex += element.Deserialize(serialized, curIndex);
                    points.Add(element);
                }
                return (curIndex - startIndex);
            }

        }
    }
}
