using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace geometry_msgs
    {
        public class PoseStamped : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "PoseStamped";
            public readonly string md5sum = "d3812c3cbc69362b77dc0b19b345f8f5";
            public std_msgs.Header header;
            public geometry_msgs.Pose pose;

            public PoseStamped ()
            {
                header = new std_msgs.Header();
                pose = new geometry_msgs.Pose();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += pose.ToStringRaw() + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                pose.Serialize(stream);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                curIndex += pose.Deserialize(serialized, curIndex);
                return (curIndex - startIndex);
            }

        }
    }
}
