using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace sensor_msgs
    {
        public class RelativeHumidity : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "RelativeHumidity";
            public readonly string md5sum = "8730015b05955b7e992ce29a2678d90f";
            public std_msgs.Header header;
            public double relative_humidity;
            public double variance;

            public RelativeHumidity ()
            {
                header = new std_msgs.Header();
                relative_humidity = 0.0;
                variance = 0.0;
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += "relative_humidity: " + Convert.ToString(relative_humidity) + "\n";
                string_rep += "variance: " + Convert.ToString(variance) + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                System.Byte[] relative_humidity_bytes = BitConverter.GetBytes(relative_humidity);
                stream.Write(relative_humidity_bytes, 0, relative_humidity_bytes.Length);
                System.Byte[] variance_bytes = BitConverter.GetBytes(variance);
                stream.Write(variance_bytes, 0, variance_bytes.Length);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                relative_humidity = BitConverter.ToDouble(serialized, curIndex);
                curIndex += BitConverter.GetBytes(relative_humidity).Length;
                variance = BitConverter.ToDouble(serialized, curIndex);
                curIndex += BitConverter.GetBytes(variance).Length;
                return (curIndex - startIndex);
            }

        }
    }
}
