using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace geometry_msgs
    {
        public class Transform : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "Transform";
            public readonly string md5sum = "ac9eff44abf714214112b05d54a3cf9b";
            public geometry_msgs.Vector3 translation;
            public geometry_msgs.Quaternion rotation;

            public Transform ()
            {
                translation = new geometry_msgs.Vector3();
                rotation = new geometry_msgs.Quaternion();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += translation.ToStringRaw() + "\n";
                string_rep += rotation.ToStringRaw() + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                translation.Serialize(stream);
                rotation.Serialize(stream);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += translation.Deserialize(serialized, curIndex);
                curIndex += rotation.Deserialize(serialized, curIndex);
                return (curIndex - startIndex);
            }

        }
    }
}
