using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace geometry_msgs
    {
        public class TwistStamped : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "TwistStamped";
            public readonly string md5sum = "98d34b0043a2093cf9d9345ab6eef12e";
            public std_msgs.Header header;
            public geometry_msgs.Twist twist;

            public TwistStamped ()
            {
                header = new std_msgs.Header();
                twist = new geometry_msgs.Twist();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += header.ToStringRaw() + "\n";
                string_rep += twist.ToStringRaw() + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                header.Serialize(stream);
                twist.Serialize(stream);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += header.Deserialize(serialized, curIndex);
                curIndex += twist.Deserialize(serialized, curIndex);
                return (curIndex - startIndex);
            }

        }
    }
}
