using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

//////////////////////////////////////////////////
/////    AUTOGENERATED MESSAGE DEFINITION    /////
//////////////////////////////////////////////////
/////         DO NOT MODIFY BY HAND!         /////
//////////////////////////////////////////////////

namespace ROS_CS
{
    namespace geometry_msgs
    {
        public class Wrench : ROS_CS.Core.BaseMessage
        {
            public readonly string typeID = "Wrench";
            public readonly string md5sum = "4f539cf138b23283b520fd271b567936";
            public geometry_msgs.Vector3 force;
            public geometry_msgs.Vector3 torque;

            public Wrench ()
            {
                force = new geometry_msgs.Vector3();
                torque = new geometry_msgs.Vector3();
            }

            public override string ToString ()
            {
                return ROS_CS.Core.PrettyPrinter.PrettyPrint(ToStringRaw());
            }

            public override string ToStringRaw ()
            {
                string string_rep = typeID + ":\n";
                string_rep += force.ToStringRaw() + "\n";
                string_rep += torque.ToStringRaw() + "\n";
                return string_rep;
            }

            public override void Serialize(MemoryStream stream)
            {
                force.Serialize(stream);
                torque.Serialize(stream);
            }

            public override int Deserialize(System.Byte[] serialized)
            {
                return Deserialize(serialized, 0);
            }

            public override int Deserialize(System.Byte[] serialized, int startIndex)
            {
                int curIndex = startIndex;
                curIndex += force.Deserialize(serialized, curIndex);
                curIndex += torque.Deserialize(serialized, curIndex);
                return (curIndex - startIndex);
            }

        }
    }
}
